version: '3.8'
services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    networks:
      - tyk

  activity-tracking:
    build:
      context: ./activity-tracking
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=development
    expose:
      - '5300'
    depends_on:
      - mongodb
    networks:
      - tyk

  analytics:
    build:
      context: ./analytics
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=development
      - MONGO_URI=mongodb://root:cfgmla23@mongodb:27017
    expose:
      - '5050'
    depends_on:
      - mongodb
    networks:
      - tyk

  authservice:
    build:
      context: ./authservice
      dockerfile: Dockerfile
    environment:
      - SPRING_DATA_MONGODB_DATABASE=test
      - SPRING_DATA_MONGODB_URI=mongodb://root:cfgmla23@mongodb:27017
    expose:
      - '8090'
    depends_on:
      - mongodb
    networks:
      - tyk

  mongodb:
    image: mongo:latest
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=cfgmla23
    expose:
      - '27017'
    volumes:
      - mongodbdata:/data/db
    networks:
      - tyk

  tyk-gateway:
    image: docker.tyk.io/tyk-gateway/tyk-gateway:v5.1.0
    ports:
      - 8080:8080
    networks:
      - tyk
    volumes:
      - ./tyk/tyk.conf:/opt/tyk-gateway/tyk.conf
      - ./tyk/apps:/opt/tyk-gateway/apps
      - ./tyk/middleware:/opt/tyk-gateway/middleware
    environment:
      - TYK_GW_SECRET=foo
    depends_on:
      - tyk-redis
    platform: linux/amd64

  tyk-redis:
    image: redis:6.2.7-alpine
    networks:
      - tyk
    ports:
      - 6379:6379

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus:/etc/prometheus
    ports:
      - '9090:9090'
    networks:
      - tyk

  grafana:
    image: grafana/grafana:latest
    ports:
      - '3100:3000'
    volumes:
      - grafana_data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=cfgmla23
      - GF_USERS_ALLOW_SIGN_UP=false
    depends_on:
      - prometheus
    networks:
      - tyk

networks:
  app-network:
    driver: bridge

  tyk:

volumes:
  mongodbdata:
  grafana_data:
