version: '3.8'
services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"

  activity-tracking:
    build:
      context: ./activity-tracking
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=development
    ports:
      - "5300:5300"
    depends_on:
      - mongodb

  analytics:
    build:
      context: ./analytics
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=development
      - MONGODB_URI=mongodb://root:cfgmla23@localhost:27017/?directConnection=true&serverSelectionTimeoutMS=2000&authSource=admin&appName=mongosh+2.0.1
    ports:
      - "6000:6000"
    depends_on:
      - mongodb

  authservice:
    build:
      context: ./authservice
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=development
    ports:
      - "8080:8080"
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=cfgmla23
      - MONGODB_URI=mongodb://root:cfgmla23@localhost:27017/?directConnection=true&serverSelectionTimeoutMS=2000&authSource=admin&appName=mongosh+2.0.1
    ports:
      - "27017:27017"
    volumes:
      - mongodbdata:/data/db

  # cypress:
  #   build:
  #     context: ./activity-tracking 
  #     dockerfile: ./cypress/Dockerfile  
  #   depends_on:
  #     - frontend
  #     - activity-tracking

volumes:
  mongodbdata: