global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'frontend'
    static_configs:
      - targets: ['frontend:3000']

  - job_name: 'activity-tracking'
    static_configs:
      - targets: ['activity-tracking:5300']

  - job_name: 'analytics'
    static_configs:
      - targets: ['analytics:5050']

  - job_name: 'authservice'
    static_configs:
      - targets: ['authservice:8090']
    metrics_path: '/actuator/prometheus'
